---
name: Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    container: debian:11
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      matrix:
        directory:
          - aardvark-dns
          - netavark
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y install curl git build-essential protobuf-compiler

      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
          target: "${{ matrix.target }}"

      - name: Configure linker
        if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
        run: |
          apt-get -y install gcc-aarch64-linux-gnu

          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" \
            >> "${GITHUB_ENV}"

      - name: Build binary
        run: |
          cd "${{ matrix.directory }}"
          cargo build --release --target "${{ matrix.target }}"
